=== falpi/osb-jwt-providers/osb/OAUTH2/Schemas/OutboundTemplates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            elementFormDefault="unqualified" attributeFormDefault="unqualified">
            
   <!-- ################################################################################ -->
   <!-- TIPI                                                                             -->
   <!-- ################################################################################ -->
     
  <xsd:simpleType name="valueType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="String"/>
      <xsd:enumeration value="Integer"/>
    </xsd:restriction>
  </xsd:simpleType>
  
   <xsd:complexType name="detailType">
      <xsd:simpleContent>
         <xsd:extension base="xsd:string">
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="type" type="valueType"  use="required"/>
         </xsd:extension>
      </xsd:simpleContent>
   </xsd:complexType>

   <xsd:complexType name="tokenItemType">
      <xsd:sequence>
         <xsd:element name="claim" type="detailType" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" use="required" type="xsd:string"/>
   </xsd:complexType>
   
   <xsd:complexType name="requestItemType">
      <xsd:sequence>
         <xsd:element name="parameter" type="detailType" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name"     use="required" type="xsd:string"/>
      <xsd:attribute name="tokenURL" use="required" type="xsd:string"/>
   </xsd:complexType>
   
   <!-- ################################################################################ -->
   <!-- ELEMENTI                                                                         -->
   <!-- ################################################################################ -->
   
   <xsd:element name="outboundTemplates">
      <xsd:complexType>
         <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="token"   type="tokenItemType" />
            <xsd:element name="request" type="requestItemType" />
         </xsd:choice>
      </xsd:complexType>
      
      <!-- dichiara che il nome dei token template deve essere univoco -->
      <xsd:key name="tokenNameKey">
         <xsd:selector xpath="token"/>
         <xsd:field xpath="@name"/>
      </xsd:key>
      <!-- dichiara che il nome delle request template deve essere univoco -->
      <xsd:key name="requestNameKey">
         <xsd:selector xpath="request"/>
         <xsd:field xpath="@name"/>
      </xsd:key>
   </xsd:element>
   
</xsd:schema>

=== falpi/osb-jwt-providers/osb/OAUTH2/Security/OutboundTemplates.xml
<?xml version="1.0" ?>
<outboundTemplates xsi:noNamespaceSchemaLocation="../Schemas/OutboundTemplates.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

   <!-- SAMPLE: replace 00000000-0000-0000-0000-000000000000 with your tenant id and the keycloak.example.com URL with your realm -->

   <!-- Client Assertion Token -->
   <token name="standard">
      <claim name="iss" type="String">${client_id}</claim>
      <claim name="sub" type="String">${client_id}</claim>
      <claim name="aud" type="String">${token_url}</claim>
      <claim name="iat" type="Integer">${current.epoch}</claim>
      <claim name="exp" type="Integer">${current.epoch}+60</claim>
      <claim name="jti" type="String">${uuid}</claim>
   </token>

   <!-- Access Token Request with Secret (Entra ID v1) -->
   <request name="azure-secret-v1" tokenURL="https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/token">
      <parameter name="grant_type"    type="String">client_credentials</parameter>
      <parameter name="client_id"     type="String">${client_id}</parameter>
      <parameter name="client_secret" type="String">${client_secret}</parameter>
      <parameter name="resource"      type="String">${resource}</parameter>
   </request>

   <!-- Access Token Request with Assertion (Entra ID v1) -->
   <request name="azure-assert-v1" tokenURL="https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/token">
      <parameter name="grant_type"            type="String">client_credentials</parameter>
      <parameter name="client_id"             type="String">${client_id}</parameter>
      <parameter name="client_assertion_type" type="String">urn:ietf:params:oauth:client-assertion-type:jwt-bearer</parameter>
      <parameter name="client_assertion"      type="String">${client_assertion}</parameter>
      <parameter name="resource"              type="String">${resource}</parameter>
   </request>

   <!-- Access Token Request with Assertion (Entra ID v2) -->
   <request name="azure-assert-v2" tokenURL="https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/v2.0/token">
      <parameter name="grant_type"            type="String">client_credentials</parameter>
      <parameter name="client_id"             type="String">${client_id}</parameter>
      <parameter name="client_assertion_type" type="String">urn:ietf:params:oauth:client-assertion-type:jwt-bearer</parameter>
      <parameter name="client_assertion"      type="String">${client_assertion}</parameter>
      <parameter name="scope"                 type="String">${scope}</parameter>
   </request>

   <!-- Access Token Request with Assertion (Keycloak) -->
   <request name="keycloak-assert" tokenURL="https://keycloak.example.com/realms/example-realm/protocol/openid-connect/token">
      <parameter name="grant_type"            type="String">client_credentials</parameter>
      <parameter name="client_id"             type="String">${client_id}</parameter>
      <parameter name="client_assertion_type" type="String">urn:ietf:params:oauth:client-assertion-type:jwt-bearer</parameter>
      <parameter name="client_assertion"      type="String">${client_assertion}</parameter>
   </request>

</outboundTemplates>
